title: "ComputerScience"
summary: "hands-on learning"
topics: ["ComputerScience"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
  - example3
  - example4
  - example5
  - example6
  - example7
  - example8
  - example9
  - example10
  - example11
  - example12
  - example13
  - example14
  - example15
  - example16
  - example17
  - example18
  - example19
  - example20
  - example21
  - example22
  - example23
  - example24
  - example25
  - example26
  